/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Gerenciador;
import Observer.Observer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Joao
 */
public class SimulacaoTrafego extends javax.swing.JFrame implements Observer {
    
    private int numeroCarros;
    private int intervaloInsercao;
    private int modo;
    private File arquivo;
    private Gerenciador gerenciador;
    /**
     * Creates new form SimulacaoTrafego
     */
    public SimulacaoTrafego(int numeroCarros, int intervaloInsercao, int modo, File arquivo) {
        this.numeroCarros = numeroCarros;
        this.intervaloInsercao = intervaloInsercao;
        this.modo = modo;
        this.arquivo = arquivo;
        
        gerenciador = Gerenciador.getInstance();
        this.gerenciador.escolherMatriz(arquivo);
        gerenciador.lerMatriz(modo);
        gerenciador.addObservador((Observer) this);
        initComponents();
        setBounds(200, 200, 1280, 720);
        carregaMatriz();
        btnParar.setEnabled(false);
        btnPararImed.setEnabled(false);
        
        
        setBounds(200, 200, 750, 720);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setLayout(new BorderLayout());
        
    }
    
    @Override
    public void notificarEstradaAlterada() {
        repaint();
    }
    
    @Override
    public void notificarSimulacaoEncerrada() {
        JOptionPane.showMessageDialog(null, "Simulacao Encerrada\n"
                                                + "Quantidade de carros solicitados: " + gerenciador.getQuantidadeDeVeiculos()+ "\n"
                                                + "Quantidade de carros criados: " + gerenciador.getVeiculosGerados());
        btnIniciar.setEnabled(true);
        btnParar.setEnabled(false);
        btnVoltar.setEnabled(true);
    }
    
    public void carregaMatriz(){
        
        trafegoTable.setModel(new EstradaTableModel());
        for(int x = 0; x < trafegoTable.getColumnModel().getColumnCount(); x++){
            trafegoTable.getColumnModel().getColumn(x).setWidth(40);  
//            trafegoTable.getColumnModel().getColumn(x).setMinWidth(30);
//            trafegoTable.getColumnModel().getColumn(x).setMaxWidth(30);
        }
//        trafegoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
//        trafegoTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
//        trafegoTable.setShowHorizontalLines(false);
//        trafegoTable.setShowVerticalLines(false);
//        trafegoTable.getTableHeader().setResizingAllowed(false);
//        trafegoTable.getTableHeader().setReorderingAllowed(false);

        
        trafegoTable.setRowHeight(23);
        trafegoTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        trafegoTable.setShowGrid(false);
//        trafegoTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        trafegoTable.setDefaultRenderer(Object.class, new EstradaRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trafegoTable = new javax.swing.JTable();
        btnPararImed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(756, 541));
        setMinimumSize(new java.awt.Dimension(756, 541));
        setPreferredSize(new java.awt.Dimension(780, 482));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMULADOR DE TRÁFEGO EM MALHA VIÁRIA");
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);

        btnVoltar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnParar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        trafegoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        trafegoTable.setAutoscrolls(false);
        trafegoTable.setEnabled(false);
        trafegoTable.setTableHeader(null);
        trafegoTable.setRowHeight(35);
        trafegoTable.setShowGrid(false);
        trafegoTable.setDefaultRenderer(Object.class, new DefaultTableCellRendererMalha());
        trafegoTable.setGridColor(Color.BLACK);
        jScrollPane1.setViewportView(trafegoTable);

        btnPararImed.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnPararImed.setText("Parar Imed.");
        btnPararImed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararImedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPararImed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnIniciar)
                    .addComponent(btnParar)
                    .addComponent(btnPararImed))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        // TODO add your handling code here:
        
        encerrarSimulacao();
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        if((intervaloInsercao > 0) && (numeroCarros > 0)){
            iniciarSimulacao();
            gerenciador.reset();
            gerenciador.iniciarSimulacao(numeroCarros, intervaloInsercao, modo);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Intervalo ou Número de Veículos inválido");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPararImedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararImedActionPerformed
        // TODO add your handling code here:
        btnParar.setEnabled(false);
        btnPararImed.setEnabled(false);
        btnIniciar.setEnabled(true);
        btnVoltar.setEnabled(true);
        gerenciador.encerrarSimulacaoImediatamente();
    }//GEN-LAST:event_btnPararImedActionPerformed
    
    public void iniciarSimulacao(){
        btnIniciar.setEnabled(false);
        btnParar.setEnabled(true);
        btnPararImed.setEnabled(true);
        btnVoltar.setEnabled(false);
    }
    
    public void encerrarSimulacao(){
        btnParar.setEnabled(false);
        btnPararImed.setEnabled(false);
        btnIniciar.setEnabled(true);
        btnVoltar.setEnabled(true);
        gerenciador.encerrarSimulacao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPararImed;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trafegoTable;
    // End of variables declaration//GEN-END:variables

    class EstradaTableModel extends AbstractTableModel {
        
        private static final long serialVersionUID = 1L;
        
        @Override
        public int getRowCount() {
            return gerenciador.getColunaCount();
        }

        @Override
        public int getColumnCount() {
            return gerenciador.getLinhaCount();
        }

        @Override
        public Object getValueAt(int i, int i1) {
            return gerenciador.getImageMatriz(i, i1);
        }
    }
    
    class EstradaRenderer extends DefaultTableCellRenderer {

        private static final long serialVersionUID = 1L;

        public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus, int row,
                int column) {

            setIcon((ImageIcon) value);

            return this;
        }
    }
}
